spring:
  application:
    name: retail-discount-engine
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:retail_discount_engine_db
  h2:
    console:
      enabled: true
server:
  port: 8000
